// Common first names, 6+ letters, lowercase a-z only. These are paid at any
// length ($150/yr founding) because they're scarce the way short names are.
// Names of 3-5 letters are priced by length in priceCentsFor and don't belong here.
// Curated from common US (SSA), Spanish, Italian, French, German, Indian,
// Arabic, Hebrew, and Japanese given names. Add freely; keep it sorted.
export const PAID_FIRST_NAMES: ReadonlySet<string> = new Set([
  "aaliyah", "abigail", "abraham", "abrahim", "adaline", "adalyn", "addison", "adelaide",
  "adelina", "adeline", "adelyn", "aditya", "adrian", "adriana", "adriano", "adriel", "adrienne",
  "agustin", "ainsley", "aishwarya", "akshay", "alaina", "alanna", "alastair", "albert", "alberto",
  "alejandra", "alejandro", "alessandra", "alessandro", "alexander", "alexandra", "alexandre",
  "alexandria", "alexia", "alexis", "alfonso", "alfred", "alfredo", "alicia", "alison", "alissa",
  "allison", "alonso", "alonzo", "alvaro", "alyssa", "amanda", "amelia", "amelie", "amiyah",
  "anabel", "ananya", "anastasia", "anders", "anderson", "andrea", "andreas", "andres", "andrew",
  "andriy", "angela", "angelica", "angelina", "angelique", "angelo", "aniyah", "anjali", "annabel",
  "annabelle", "annalise", "annette", "annika", "ansley", "anthony", "antoine", "antonia",
  "antonio", "antony", "arabella", "araceli", "archer", "ariana", "arianna", "ariella", "arielle",
  "armando", "armani", "arnold", "arthur", "arturo", "arvind", "ashley", "ashlyn", "ashton",
  "astrid", "athena", "aubree", "aubrey", "audrey", "august", "augustine", "augusto", "aurelio",
  "aurora", "austin", "autumn", "avraham", "ayesha", "bailey", "barbara", "barrett", "bartholomew",
  "baylor", "beatrice", "beatriz", "beckett", "beckham", "belinda", "benedict", "benjamin",
  "bennett", "benson", "bentley", "bernard", "bernardo", "bernice", "bertha", "bethany", "beverly",
  "bianca", "binyamin", "blanca", "bonnie", "bradley", "brandon", "braxton", "brayden", "brenda",
  "brendan", "brenna", "brennan", "briana", "brianna", "bridget", "bridgette", "brielle",
  "brittany", "brittney", "brooke", "brooklyn", "brooks", "bryant", "bryson", "caiden", "caitlin",
  "callie", "calvin", "camden", "cameron", "camila", "camille", "camilo", "candace", "candice",
  "caridad", "carina", "carlos", "carlotta", "carlton", "carmela", "carmelo", "carmen", "carolina",
  "caroline", "carolyn", "carson", "carter", "casandra", "cassandra", "cassidy", "catalina",
  "caterina", "catherine", "cecilia", "cedric", "celeste", "celestine", "chance", "chandler",
  "chantal", "charlene", "charles", "charlie", "charlotte", "chelsea", "cheryl", "chester",
  "cheyenne", "chiara", "christian", "christina", "christine", "christopher", "cierra", "claire",
  "clarence", "clarissa", "claudia", "claudio", "clayton", "clement", "clemente", "clifford",
  "clifton", "clinton", "colette", "colleen", "collin", "colton", "connor", "conrad", "constance",
  "constanza", "cooper", "corbin", "cordelia", "corinne", "cornelius", "cristian", "cristina",
  "cristobal", "crystal", "curtis", "cynthia", "dakota", "dalila", "dallas", "dalton", "damian",
  "damien", "daniel", "daniela", "daniella", "danielle", "danilo", "daphne", "darius", "darlene",
  "darren", "darwin", "dashiell", "dawson", "dayana", "deacon", "deandre", "deborah", "declan",
  "deepak", "deirdre", "delaney", "delilah", "delores", "demetrius", "denise", "dennis", "denver",
  "desiree", "desmond", "destiny", "dexter", "dillon", "dimitri", "dolores", "dominic", "dominick",
  "dominique", "donald", "donovan", "doreen", "dorian", "dorothy", "douglas", "duncan", "dustin",
  "dwayne", "dwight", "easton", "edmund", "eduardo", "edward", "efrain", "eileen", "elaina",
  "elaine", "eleanor", "eliana", "eliezer", "elijah", "elisabeth", "eliseo", "elisheva",
  "elizabeth", "elliot", "elliott", "eloise", "elvira", "emanuel", "emerson", "emilia", "emiliano",
  "emilio", "emmanuel", "emmeline", "emmett", "enrique", "ephraim", "ernest", "ernesto",
  "esmeralda", "esperanza", "esteban", "estela", "estella", "estelle", "esther", "estrella",
  "eugene", "eugenia", "eugenio", "eunice", "evangeline", "evelyn", "everett", "everly", "ezekiel",
  "ezequiel", "fabian", "fabiola", "fabrizio", "fatima", "federico", "felicia", "felicity",
  "felipe", "fernanda", "fernando", "finley", "finnegan", "fletcher", "florence", "florencia",
  "forrest", "frances", "francesca", "francesco", "francine", "francis", "francisca", "francisco",
  "franklin", "frederic", "frederick", "gabriel", "gabriela", "gabriella", "gabrielle", "garrett",
  "gaurav", "genesis", "genevieve", "geoffrey", "george", "georgia", "georgina", "gerald",
  "geraldine", "gerard", "gerardo", "german", "gertrude", "gianna", "gideon", "gilbert",
  "gilberto", "gillian", "giovanna", "giovanni", "giselle", "gloria", "gonzalo", "gordon",
  "gracie", "graciela", "graham", "grayson", "gregory", "gretchen", "griffin", "guadalupe",
  "guillermo", "gunnar", "gustavo", "gwendolyn", "hadley", "hailey", "hallie", "hamilton",
  "hannah", "harley", "harmony", "harold", "harper", "harriet", "harrison", "haruto", "harvey",
  "hassan", "hattie", "hayden", "haylee", "heather", "hector", "helena", "helene", "henrietta",
  "herbert", "herman", "hermione", "hilary", "hillary", "hinata", "hiroshi", "holden", "hollis",
  "horacio", "howard", "hudson", "hunter", "hussein", "ibrahim", "ignacio", "imogen", "ingrid",
  "irving", "isabel", "isabela", "isabella", "isabelle", "isadora", "isaiah", "ishaan", "isidro",
  "ismael", "israel", "ivanna", "jacinta", "jackson", "jacqueline", "jaiden", "jameson", "janelle",
  "janice", "jasmine", "jasper", "javier", "jaxson", "jayden", "jaylen", "jayson", "jazmin",
  "jeanette", "jeffery", "jeffrey", "jennifer", "jeremiah", "jeremy", "jerome", "jessica",
  "jillian", "jimena", "joanna", "joaquin", "jocelyn", "johanna", "johnathan", "johnny", "jolene",
  "jonathan", "jordan", "jordyn", "josefina", "joseph", "josephine", "joshua", "josiah", "journey",
  "juanita", "judith", "julian", "juliana", "julianna", "julianne", "juliet", "juliette",
  "julissa", "junior", "juniper", "justin", "justine", "kaiden", "kailey", "kaitlyn", "kamila",
  "karina", "karter", "kassandra", "katarina", "katelyn", "katharine", "katherine", "kathleen",
  "kathryn", "kayden", "kaylee", "kayleigh", "kaylin", "keegan", "kellan", "kelsey", "kendall",
  "kendra", "kennedy", "kenneth", "kenzie", "khalid", "khalil", "kieran", "kimberly", "kingsley",
  "kingston", "kinsley", "kirsten", "krishna", "kristen", "kristian", "kristin", "kristina",
  "kristopher", "lachlan", "lailah", "lakshman", "lakshmi", "landon", "laurel", "lauren",
  "laurence", "lawrence", "leandro", "leilani", "leland", "lennox", "leonard", "leonardo",
  "leonel", "leonie", "leonor", "leopold", "leslie", "lester", "leticia", "lilian", "liliana",
  "lillian", "lillie", "lincoln", "lindsay", "lindsey", "linnea", "lionel", "lisandro", "london",
  "lorena", "lorenzo", "loretta", "lorraine", "louisa", "louise", "lourdes", "lucian", "luciana",
  "luciano", "lucille", "lucinda", "ludwig", "lyndon", "mackenzie", "maddox", "madeleine",
  "madeline", "madelyn", "madison", "magdalena", "maggie", "magnolia", "mahmoud", "maisie",
  "makayla", "malachi", "malcolm", "mallory", "manish", "manuel", "manuela", "marcel", "marcela",
  "marcelo", "marcia", "marcos", "marcus", "margaret", "margarita", "margaux", "margot",
  "marguerite", "mariah", "mariam", "mariana", "marianne", "marilyn", "marina", "marion", "marisa",
  "marisol", "marissa", "maritza", "marjorie", "marlee", "marlene", "marley", "marlon", "marshall",
  "martha", "martin", "martina", "marvin", "maryam", "matias", "matilda", "matteo", "matthew",
  "matthias", "maureen", "maurice", "mauricio", "maverick", "maximilian", "maximo", "maximus",
  "maxine", "maxwell", "maybelle", "mckenna", "mckenzie", "mckinley", "meadow", "meghan",
  "melanie", "melinda", "melissa", "melody", "melvin", "memphis", "menachem", "mendel", "mercedes",
  "meredith", "micaela", "michael", "michaela", "micheal", "michelle", "miguel", "mikaela",
  "mikayla", "milagros", "milena", "miller", "millie", "milton", "minerva", "miracle", "miranda",
  "miriam", "mitchell", "modesto", "mohamed", "mohammad", "mohammed", "monica", "monique",
  "monroe", "montgomery", "montserrat", "morgan", "moriah", "muhammad", "murphy", "murray",
  "mustafa", "nadine", "naftali", "nasser", "natalia", "natalie", "natasha", "nathan", "nathanael",
  "nathaniel", "nayeli", "nechama", "nehemiah", "nellie", "nelson", "nevaeh", "nicholas",
  "nicolas", "nicole", "nicolette", "nikhil", "nikolai", "nikolas", "noelle", "norman", "oakley",
  "octavia", "octavio", "odette", "oliver", "olivia", "ophelia", "orlando", "osvaldo", "oswaldo",
  "palmer", "paloma", "pamela", "parker", "patrice", "patricia", "patrick", "paulina", "pauline",
  "paxton", "payton", "penelope", "peyton", "philip", "phillip", "phoebe", "phoenix", "phyllis",
  "pierce", "pierre", "porter", "pranav", "presley", "preston", "princeton", "priscilla",
  "priyanka", "quentin", "quincy", "quinton", "rachael", "rachel", "raelynn", "rafael", "raheem",
  "raiden", "rainer", "rajesh", "rakesh", "ramesh", "ramiro", "ramona", "ramsey", "randall",
  "randolph", "raphael", "raquel", "rashad", "rashid", "raymond", "raymundo", "reagan", "rebecca",
  "rebekah", "regina", "reginald", "remington", "renata", "reuben", "reynaldo", "rhiannon",
  "ricardo", "richard", "rigoberto", "robert", "roberta", "roberto", "roderick", "rodney",
  "rodolfo", "rodrigo", "rogelio", "roland", "rolando", "ronald", "ronaldo", "rosalie", "rosalind",
  "rosalinda", "rosalyn", "rosario", "roselyn", "rosemary", "roxana", "roxanne", "rudolph",
  "russell", "ryland", "ryleigh", "saanvi", "sabrina", "sakura", "salome", "salvador", "salvatore",
  "samantha", "samara", "samira", "samson", "samuel", "sandra", "sanjay", "santiago", "santino",
  "saoirse", "satoshi", "savannah", "sawyer", "saylor", "scarlett", "sebastian", "selena",
  "selina", "seraphina", "serena", "serenity", "sergio", "seymour", "shannon", "sharon", "sheila",
  "shelby", "sheldon", "shelley", "sherman", "sherry", "shiloh", "shimon", "shirley", "shlomo",
  "shmuel", "shreya", "siddharth", "sidney", "sienna", "sierra", "silvia", "simeon", "simone",
  "skylar", "skyler", "sloane", "solomon", "sophia", "sophie", "soraya", "spencer", "stacey",
  "stanley", "stefan", "stefanie", "stefano", "stella", "stephanie", "stephen", "sterling",
  "steven", "stewart", "stuart", "sullivan", "summer", "suresh", "susana", "susanna", "susannah",
  "sutton", "suzanne", "sydney", "sylvia", "sylvie", "tabitha", "takashi", "tamara", "tanner",
  "tatiana", "taylor", "teagan", "teodoro", "teresa", "terrance", "terrence", "thaddeus",
  "theodora", "theodore", "theresa", "thiago", "thomas", "tiffany", "timothy", "tobias", "tracey",
  "travis", "trevor", "trinity", "tristan", "tristen", "tucker", "tyrone", "ulises", "ulysses",
  "ursula", "valentin", "valentina", "valentino", "valeria", "valerie", "vanessa", "vaughn",
  "veronica", "vicente", "victor", "victoria", "vikram", "vincent", "vincenzo", "violet",
  "violeta", "virginia", "vivaan", "vivian", "viviana", "vivienne", "vladimir", "walker",
  "wallace", "walter", "warren", "wendell", "wesley", "weston", "whitney", "wilder", "wilfred",
  "wilhelm", "william", "willie", "willow", "wilson", "winifred", "winnie", "winston", "xander",
  "xavier", "ximena", "yaakov", "yaretzi", "yasmin", "yasmine", "yehuda", "yesenia", "yisroel",
  "yitzchak", "yolanda", "youssef", "yvette", "yvonne", "zachariah", "zachary", "zackary",
  "zainab", "zander", "zayden",
]);
